# Generated by Django 3.0.8 on 2020-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200727_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercards',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='usercards',
            name='name',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set'], name='cards_card_set_b54906_idx'),
        ),
    ]
