# Generated by Django 3.0.8 on 2020-07-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20200729_1421'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='cards_card_name_a125cc_idx'),
        ),
    ]
