# Generated by Django 3.0.8 on 2020-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20200729_1536'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_color_l_666799_idx',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_name_a125cc_idx',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['color_lookup', 'name', 'set'], name='cards_card_color_l_4fd352_idx'),
        ),
    ]
