# Generated by Django 3.0.8 on 2020-07-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20200729_1538'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_color_l_4fd352_idx',
        ),
    ]
