# Generated by Django 3.0.8 on 2020-07-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_auto_20200730_1622'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_set_b54906_idx',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set', 'color_lookup'], name='cards_card_set_ce0598_idx'),
        ),
    ]
