# Generated by Django 3.0.8 on 2020-07-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20200730_1940'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='cards_card_set_56fdc1_idx',
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set', 'color_lookup', 'name', 'id', 'img_url'], name='cards_card_set_513cb1_idx'),
        ),
    ]
