# Generated by Django 3.0.8 on 2020-07-31 19:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20200730_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='card_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
