# Generated by Django 3.0.8 on 2020-07-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0017_auto_20200731_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='card_list',
        ),
    ]
