# Generated by Django 3.0.8 on 2020-08-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_commander_card_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commander',
            name='card_list',
        ),
    ]
