# Generated by Django 3.0.8 on 2020-08-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_commander_card_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
