# Generated by Django 3.0.8 on 2020-08-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_card_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name', 'id', 'img_url', 'type'], name='inventory_comparison'),
        ),
    ]
